# GET https://www.volleyball.world/en/vnl/women/teams HTTP/1.
# Content-Type: application/json

# GET https://www.volleyball.world/en/vnl/women/teams HTTP/1.1
# Content-Type:  application/json

# {
#     "test": "test"
# }

# GET https://www.volleyball.world/en/vnl/women/teams/dom-dominican%20republic/team_roster HTTP/1.1

GET https://www.volleyball.world/en/vnl/women/teams/ita-italy/players/cristina-chirichella?id=71297 HTTP/1.1